export { adminSettingsRouter } from "./settings";
export { adminStatsRouter } from "./stats";
export { adminUsersRouter } from "./users";
export { adminSiteConfigRouter } from "./site-config";
export { adminActivityRouter } from "./activity";
export { adminContactsRouter, publicContactsRouter } from "./contacts";
export { adminTestimonialsRouter } from "./testimonials";
export { adminAlumniRouter } from "./alumni";
export { adminGalleryRouter } from "./gallery";
export { adminEventsRouter } from "./events";
export { adminResourcesRouter } from "./resources";
export { adminPromosRouter } from "./promos";
