/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniRouteImport } from './routes/testimoni'
import { Route as SyaratKetentuanRouteImport } from './routes/syarat-ketentuan'
import { Route as SertifikasiRouteImport } from './routes/sertifikasi'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as MitraRouteImport } from './routes/mitra'
import { Route as MetodeRouteImport } from './routes/metode'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as KebijakanPrivasiRouteImport } from './routes/kebijakan-privasi'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventRouteImport } from './routes/event'
import { Route as CaraDaftarRouteImport } from './routes/cara-daftar'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProgramsRouteRouteImport } from './routes/programs/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProgramsSlugRouteImport } from './routes/programs/$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TestimoniRoute = TestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratKetentuanRoute = SyaratKetentuanRouteImport.update({
  id: '/syarat-ketentuan',
  path: '/syarat-ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const SertifikasiRoute = SertifikasiRouteImport.update({
  id: '/sertifikasi',
  path: '/sertifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const MitraRoute = MitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodeRoute = MetodeRouteImport.update({
  id: '/metode',
  path: '/metode',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanPrivasiRoute = KebijakanPrivasiRouteImport.update({
  id: '/kebijakan-privasi',
  path: '/kebijakan-privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const CaraDaftarRoute = CaraDaftarRouteImport.update({
  id: '/cara-daftar',
  path: '/cara-daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRouteRoute = ProgramsRouteRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/programs': typeof ProgramsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/alumni': typeof AlumniRoute
  '/cara-daftar': typeof CaraDaftarRoute
  '/event': typeof EventRoute
  '/faq': typeof FaqRoute
  '/founder': typeof FounderRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/metode': typeof MetodeRoute
  '/mitra': typeof MitraRoute
  '/promo': typeof PromoRoute
  '/resources': typeof ResourcesRoute
  '/sertifikasi': typeof SertifikasiRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/testimoni': typeof TestimoniRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alumni': typeof AlumniRoute
  '/cara-daftar': typeof CaraDaftarRoute
  '/event': typeof EventRoute
  '/faq': typeof FaqRoute
  '/founder': typeof FounderRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/metode': typeof MetodeRoute
  '/mitra': typeof MitraRoute
  '/promo': typeof PromoRoute
  '/resources': typeof ResourcesRoute
  '/sertifikasi': typeof SertifikasiRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/testimoni': typeof TestimoniRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/programs': typeof ProgramsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/alumni': typeof AlumniRoute
  '/cara-daftar': typeof CaraDaftarRoute
  '/event': typeof EventRoute
  '/faq': typeof FaqRoute
  '/founder': typeof FounderRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/metode': typeof MetodeRoute
  '/mitra': typeof MitraRoute
  '/promo': typeof PromoRoute
  '/resources': typeof ResourcesRoute
  '/sertifikasi': typeof SertifikasiRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/testimoni': typeof TestimoniRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/programs'
    | '/about'
    | '/alumni'
    | '/cara-daftar'
    | '/event'
    | '/faq'
    | '/founder'
    | '/galeri'
    | '/jadwal'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/metode'
    | '/mitra'
    | '/promo'
    | '/resources'
    | '/sertifikasi'
    | '/syarat-ketentuan'
    | '/testimoni'
    | '/admin/login'
    | '/api/chat'
    | '/programs/$slug'
    | '/admin/'
    | '/programs/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alumni'
    | '/cara-daftar'
    | '/event'
    | '/faq'
    | '/founder'
    | '/galeri'
    | '/jadwal'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/metode'
    | '/mitra'
    | '/promo'
    | '/resources'
    | '/sertifikasi'
    | '/syarat-ketentuan'
    | '/testimoni'
    | '/admin/login'
    | '/api/chat'
    | '/programs/$slug'
    | '/admin'
    | '/programs'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/programs'
    | '/about'
    | '/alumni'
    | '/cara-daftar'
    | '/event'
    | '/faq'
    | '/founder'
    | '/galeri'
    | '/jadwal'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/metode'
    | '/mitra'
    | '/promo'
    | '/resources'
    | '/sertifikasi'
    | '/syarat-ketentuan'
    | '/testimoni'
    | '/admin/login'
    | '/api/chat'
    | '/programs/$slug'
    | '/admin/'
    | '/programs/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ProgramsRouteRoute: typeof ProgramsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AlumniRoute: typeof AlumniRoute
  CaraDaftarRoute: typeof CaraDaftarRoute
  EventRoute: typeof EventRoute
  FaqRoute: typeof FaqRoute
  FounderRoute: typeof FounderRoute
  GaleriRoute: typeof GaleriRoute
  JadwalRoute: typeof JadwalRoute
  KebijakanPrivasiRoute: typeof KebijakanPrivasiRoute
  KontakRoute: typeof KontakRoute
  MetodeRoute: typeof MetodeRoute
  MitraRoute: typeof MitraRoute
  PromoRoute: typeof PromoRoute
  ResourcesRoute: typeof ResourcesRoute
  SertifikasiRoute: typeof SertifikasiRoute
  SyaratKetentuanRoute: typeof SyaratKetentuanRoute
  TestimoniRoute: typeof TestimoniRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimoni': {
      id: '/testimoni'
      path: '/testimoni'
      fullPath: '/testimoni'
      preLoaderRoute: typeof TestimoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-ketentuan': {
      id: '/syarat-ketentuan'
      path: '/syarat-ketentuan'
      fullPath: '/syarat-ketentuan'
      preLoaderRoute: typeof SyaratKetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sertifikasi': {
      id: '/sertifikasi'
      path: '/sertifikasi'
      fullPath: '/sertifikasi'
      preLoaderRoute: typeof SertifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitra': {
      id: '/mitra'
      path: '/mitra'
      fullPath: '/mitra'
      preLoaderRoute: typeof MitraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metode': {
      id: '/metode'
      path: '/metode'
      fullPath: '/metode'
      preLoaderRoute: typeof MetodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan-privasi': {
      id: '/kebijakan-privasi'
      path: '/kebijakan-privasi'
      fullPath: '/kebijakan-privasi'
      preLoaderRoute: typeof KebijakanPrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cara-daftar': {
      id: '/cara-daftar'
      path: '/cara-daftar'
      fullPath: '/cara-daftar'
      preLoaderRoute: typeof CaraDaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ProgramsRouteRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteRouteChildren: ProgramsRouteRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteRouteWithChildren = ProgramsRouteRoute._addFileChildren(
  ProgramsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ProgramsRouteRoute: ProgramsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AlumniRoute: AlumniRoute,
  CaraDaftarRoute: CaraDaftarRoute,
  EventRoute: EventRoute,
  FaqRoute: FaqRoute,
  FounderRoute: FounderRoute,
  GaleriRoute: GaleriRoute,
  JadwalRoute: JadwalRoute,
  KebijakanPrivasiRoute: KebijakanPrivasiRoute,
  KontakRoute: KontakRoute,
  MetodeRoute: MetodeRoute,
  MitraRoute: MitraRoute,
  PromoRoute: PromoRoute,
  ResourcesRoute: ResourcesRoute,
  SertifikasiRoute: SertifikasiRoute,
  SyaratKetentuanRoute: SyaratKetentuanRoute,
  TestimoniRoute: TestimoniRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
